//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.09 at 10:43:29 AM IST 
//


package com.intuit.accountant.services.dcm.model.wms;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for job complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="job">
 *   &lt;complexContent>
 *     &lt;extension base="{http://services.intuit.com/accountant/v1}entity">
 *       &lt;sequence>
 *         &lt;element name="offeringId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assignedBy" type="{http://services.intuit.com/accountant/v1}identity" minOccurs="0"/>
 *         &lt;element name="assignedTo" type="{http://services.intuit.com/accountant/v1}identity" minOccurs="0"/>
 *         &lt;element name="inServiceTo" type="{http://services.intuit.com/accountant/v1}identity" minOccurs="0"/>
 *         &lt;element name="inContextOf" type="{http://services.intuit.com/accountant/v1}identity" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceApplication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="relevantYear" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "job", namespace = "http://services.intuit.com/accountant/v1", propOrder = {
    "offeringId",
    "name",
    "description",
    "summary",
    "notes",
    "report",
    "assignedBy",
    "assignedTo",
    "inServiceTo",
    "inContextOf",
    "status",
    "type",
    "sourceApplication",
    "priority",
    "dueDate",
    "relevantYear",
    "content"
})
public class Job
    extends Entity
{

    @XmlElement(namespace = "http://services.intuit.com/accountant/v1", required = true)
    protected String offeringId;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String name;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String description;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String summary;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String notes;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String report;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected Identity assignedBy;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected Identity assignedTo;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected Identity inServiceTo;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected Identity inContextOf;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String status;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String type;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String sourceApplication;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String priority;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger relevantYear;
    @XmlElement(namespace = "http://services.intuit.com/accountant/v1")
    protected String content;

    /**
     * Gets the value of the offeringId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOfferingId() {
        return offeringId;
    }

    /**
     * Sets the value of the offeringId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOfferingId(String value) {
        this.offeringId = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the summary property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the notes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the report property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReport(String value) {
        this.report = value;
    }

    /**
     * Gets the value of the assignedBy property.
     *
     * @return
     *     possible object is
     *     {@link Identity }
     *
     */
    public Identity getAssignedBy() {
        return assignedBy;
    }

    /**
     * Sets the value of the assignedBy property.
     *
     * @param value
     *     allowed object is
     *     {@link Identity }
     *
     */
    public void setAssignedBy(Identity value) {
        this.assignedBy = value;
    }

    /**
     * Gets the value of the assignedTo property.
     *
     * @return
     *     possible object is
     *     {@link Identity }
     *
     */
    public Identity getAssignedTo() {
        return assignedTo;
    }

    /**
     * Sets the value of the assignedTo property.
     *
     * @param value
     *     allowed object is
     *     {@link Identity }
     *
     */
    public void setAssignedTo(Identity value) {
        this.assignedTo = value;
    }

    /**
     * Gets the value of the inServiceTo property.
     *
     * @return
     *     possible object is
     *     {@link Identity }
     *
     */
    public Identity getInServiceTo() {
        return inServiceTo;
    }

    /**
     * Sets the value of the inServiceTo property.
     *
     * @param value
     *     allowed object is
     *     {@link Identity }
     *
     */
    public void setInServiceTo(Identity value) {
        this.inServiceTo = value;
    }

    /**
     * Gets the value of the inContextOf property.
     *
     * @return
     *     possible object is
     *     {@link Identity }
     *
     */
    public Identity getInContextOf() {
        return inContextOf;
    }

    /**
     * Sets the value of the inContextOf property.
     *
     * @param value
     *     allowed object is
     *     {@link Identity }
     *
     */
    public void setInContextOf(Identity value) {
        this.inContextOf = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the sourceApplication property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceApplication() {
        return sourceApplication;
    }

    /**
     * Sets the value of the sourceApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceApplication(String value) {
        this.sourceApplication = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the relevantYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelevantYear() {
        return relevantYear;
    }

    /**
     * Sets the value of the relevantYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelevantYear(BigInteger value) {
        this.relevantYear = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

}
