apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "reminders-service.fullname" . }}
  labels:
    app: {{ template "reminders-service.name" . }}
    chart: {{ template "reminders-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "reminders-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "reminders-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep", "300" ]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /reminders-service/v1/health/full
              port: http
          readinessProbe:
            httpGet:
              path: /reminders-service/support/v1/health/full
              port: http
          env:
{{- range $key, $value := .Values.environment }}
            - name: {{ $key }}
              value: {{ $value }}
{{- end}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
