# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2 # replica count

image:
  imagePullSecrets:
    - name: regsecret
  repository: nginx # image location
  tag: stable # iamge tag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080 # Port application listens on
  livenessProbePath: /reminders-service/health/full
  livenessPeriodSeconds: 10
  readinessProbePath: /reminders-service/health/full
  readinessPeriodSeconds: 120
  
secrets:
  - name: reminders-idps
    secret:
      secretName: reminders-idps

volumes:
  - name: reminders-idps
    mountPath: "/run/pcg/idps"
    readOnly: true

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx # enable to handle ingress
    kubernetes.io/tls-acme: "true" # enable to force http -> https redirect
  # ingressElb is set to the name of the elb setup by the ingress service
  ingressElb: ""
  hosts: []
    # - pr22-uisvc.walker-ppd.a.intuit.com
  tls: []
  #  - secretName: walker-ppd

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # 1024m = 1 vcpu
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  limits:
   cpu: 1024m
   memory: 3Gi

nodeSelector: {}

tolerations: []

affinity: {}

environment: {}
  # Environment variables your application needs
  # APP_ID: intuit.accountaint.blasvc
